// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A generative fill AI agent.
 *
 * - generativeFill - A function that handles the generative fill process.
 * - GenerativeFillInput - The input type for the generativeFill function.
 * - GenerativeFillOutput - The return type for the generativeFill function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerativeFillInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to fill in missing parts, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  prompt: z.string().describe('The prompt to use for generative fill.'),
});
export type GenerativeFillInput = z.infer<typeof GenerativeFillInputSchema>;

const GenerativeFillOutputSchema = z.object({
  filledPhotoDataUri: z
    .string()
    .describe('The filled photo, as a data URI with base64 encoding.'),
});
export type GenerativeFillOutput = z.infer<typeof GenerativeFillOutputSchema>;

export async function generativeFill(input: GenerativeFillInput): Promise<GenerativeFillOutput> {
  return generativeFillFlow(input);
}

const generativeFillPrompt = ai.definePrompt({
  name: 'generativeFillPrompt',
  input: {schema: GenerativeFillInputSchema},
  output: {schema: GenerativeFillOutputSchema},
  prompt: [
    {media: {url: '{{{photoDataUri}}}'}},
    {text: '{{{prompt}}}'},
  ],
  model: 'googleai/gemini-2.0-flash-preview-image-generation',
  config: {
    responseModalities: ['TEXT', 'IMAGE'],
  },
});

const generativeFillFlow = ai.defineFlow(
  {
    name: 'generativeFillFlow',
    inputSchema: GenerativeFillInputSchema,
    outputSchema: GenerativeFillOutputSchema,
  },
  async input => {
    const {media} = await generativeFillPrompt(input);
    return {filledPhotoDataUri: media!.url!};
  }
);
