
import {
  FileText,
  Image,
  ArrowRightLeft,
  PenLine,
  Globe,
  Calculator,
  FlaskConical,
  Code,
  Link as LinkIcon,
  Lock,
  CheckSquare,
  Network,
  Palette,
  ScanText,
  Folder,
  LucideIcon,
  Star,
} from 'lucide-react';

export interface Tool {
  name: string;
  slug: string;
  description: string;
  category: string;
  isImplemented?: boolean;
}

export interface Category {
  name: string;
  slug: string;
  icon: LucideIcon;
  tools: Tool[];
  color: string;
}

const tools: Tool[] = [
  // 1) PDF Tools
  { name: 'PDF to Word', slug: 'pdf-to-word', description: 'Convert PDF files to editable Word documents.', category: 'pdf-tools', isImplemented: true },
  { name: 'Word to PDF', slug: 'word-to-pdf', description: 'Convert Word documents to PDF files.', category: 'pdf-tools', isImplemented: true },
  { name: 'PDF to Excel', slug: 'pdf-to-excel', description: 'Convert PDF tables to Excel spreadsheets.', category: 'pdf-tools', isImplemented: true },
  { name: 'Excel to PDF', slug: 'excel-to-pdf', description: 'Convert Excel spreadsheets to PDF files.', category: 'pdf-tools', isImplemented: true },
  { name: 'PDF to PowerPoint', slug: 'pdf-to-powerpoint', description: 'Convert PDFs to PowerPoint presentations.', category: 'pdf-tools' },
  { name: 'PowerPoint to PDF', slug: 'powerpoint-to-pdf', description: 'Convert PowerPoint presentations to PDF.', category: 'pdf-tools' },
  { name: 'PDF to JPG', slug: 'pdf-to-jpg', description: 'Convert each PDF page to a JPG image.', category: 'pdf-tools' },
  { name: 'JPG to PDF', slug: 'jpg-to-pdf', description: 'Convert JPG images to a single PDF file.', category: 'pdf-tools' },
  { name: 'PDF to PNG', slug: 'pdf-to-png', description: 'Convert each PDF page to a PNG image.', category: 'pdf-tools' },
  { name: 'PNG to PDF', slug: 'png-to-pdf', description: 'Convert PNG images to a single PDF file.', category: 'pdf-tools' },
  { name: 'PDF to HTML', slug: 'pdf-to-html', description: 'Convert PDF documents to HTML web pages.', category: 'pdf-tools' },
  { name: 'HTML to PDF', slug: 'html-to-pdf', description: 'Convert web pages to PDF documents.', category: 'pdf-tools' },
  { name: 'PDF to TXT (Extract Text)', slug: 'pdf-to-txt', description: 'Extract plain text from your PDF files.', category: 'pdf-tools' },
  { name: 'TXT to PDF', slug: 'txt-to-pdf', description: 'Convert plain text files to PDF documents.', category: 'pdf-tools' },
  { name: 'PDF to EPUB', slug: 'pdf-to-epub', description: 'Convert PDF documents to EPUB eBooks.', category: 'pdf-tools' },
  { name: 'EPUB to PDF', slug: 'epub-to-pdf', description: 'Convert EPUB eBooks to PDF documents.', category: 'pdf-tools' },
  { name: 'PDF to RTF', slug: 'pdf-to-rtf', description: 'Convert PDF to Rich Text Format.', category: 'pdf-tools' },
  { name: 'RTF to PDF', slug: 'rtf-to-pdf', description: 'Convert Rich Text Format to PDF.', category: 'pdf-tools' },
  { name: 'Merge PDF', slug: 'merge-pdf', description: 'Combine multiple PDF files into one.', category: 'pdf-tools' },
  { name: 'Split PDF', slug: 'split-pdf', description: 'Extract specific pages or page ranges from a PDF.', category: 'pdf-tools' },
  { name: 'Compress PDF', slug: 'compress-pdf', description: 'Reduce the file size of your PDF documents.', category: 'pdf-tools' },
  { name: 'Rearrange PDF Pages', slug: 'rearrange-pdf-pages', description: 'Sort or reorder pages in your PDF.', category: 'pdf-tools' },
  { name: 'Rotate PDF Pages', slug: 'rotate-pdf-pages', description: 'Rotate all or specific pages in your PDF.', category: 'pdf-tools' },
  { name: 'Delete PDF Pages', slug: 'delete-pdf-pages', description: 'Remove unwanted pages from your PDF.', category: 'pdf-tools' },
  { name: 'Extract PDF Pages', slug: 'extract-pdf-pages', description: 'Create a new PDF from selected pages.', category: 'pdf-tools' },
  { name: 'Add Page Numbers to PDF', slug: 'add-page-numbers-to-pdf', description: 'Insert page numbers into your PDF.', category: 'pdf-tools' },
  { name: 'Add Watermark to PDF', slug: 'add-watermark-to-pdf', description: 'Add a text or image watermark to your PDF.', category: 'pdf-tools' },
  { name: 'Remove PDF Watermark', slug: 'remove-pdf-watermark', description: 'Remove watermarks from your PDF files.', category: 'pdf-tools' },
  { name: 'Add Password to PDF', slug: 'add-password-to-pdf', description: 'Protect your PDF with a password.', category: 'pdf-tools' },
  { name: 'Unlock PDF (Remove Password)', slug: 'unlock-pdf', description: 'Remove password protection from a PDF.', category: 'pdf-tools' },
  { name: 'Repair Corrupted PDF', slug: 'repair-corrupted-pdf', description: 'Attempt to fix and recover data from a damaged PDF.', category: 'pdf-tools' },
  { name: 'Flatten PDF', slug: 'flatten-pdf', description: 'Make form fields and annotations non-editable.', category: 'pdf-tools' },
  { name: 'Unflatten PDF (Make Fields Editable)', slug: 'unflatten-pdf', description: 'Attempt to make flattened PDF fields editable again.', category: 'pdf-tools' },
  { name: 'Fill & Sign PDF Forms', slug: 'fill-and-sign-pdf-forms', description: 'Complete and sign PDF forms online.', category: 'pdf-tools' },
  { name: 'Redact PDF', slug: 'redact-pdf', description: 'Permanently remove sensitive information from a PDF.', category: 'pdf-tools' },
  { name: 'PDF Metadata Viewer', slug: 'pdf-metadata-viewer', description: 'View the metadata of a PDF document.', category: 'pdf-tools' },
  { name: 'PDF Metadata Remover', slug: 'pdf-metadata-remover', description: 'Remove all metadata from a PDF document.', category: 'pdf-tools' },
  { name: 'OCR PDF (Image/PDF to Searchable)', slug: 'ocr-pdf', description: 'Make your scanned PDFs searchable and selectable.', category: 'pdf-tools' },
  { name: 'PDF Background Remover (White Background)', slug: 'pdf-background-remover', description: 'Remove the background color from a PDF.', category: 'pdf-tools' },
  { name: 'PDF Thumbnail Generator', slug: 'pdf-thumbnail-generator', description: 'Create a thumbnail image from the first page of a PDF.', category: 'pdf-tools' },
  { name: 'PDF Form Filler', slug: 'pdf-form-filler', description: 'Easily fill out PDF forms online.', category: 'pdf-tools' },
  { name: 'PDF Merge by Page Range', slug: 'pdf-merge-by-page-range', description: 'Merge specific page ranges from multiple PDFs.', category: 'pdf-tools' },
  { name: 'EPUB to Word Converter', slug: 'epub-to-word-converter', description: 'Convert EPUB files to Word documents.', category: 'pdf-tools' },
  { name: 'PDF to XPS Converter', slug: 'pdf-to-xps-converter', description: 'Convert PDF files to XPS format.', category: 'pdf-tools' },
  { name: 'PDF Background Remover (AI)', slug: 'pdf-background-remover-ai', description: 'Use AI to intelligently remove complex backgrounds from PDFs.', category: 'pdf-tools' },
  
  // 2) Image Tools
  { name: 'Background Remover', slug: 'background-remover', description: 'Remove the background from any image.', category: 'image-tools' },
  { name: 'Image Compressor', slug: 'image-compressor', description: 'Compress images to reduce file size.', category: 'image-tools', isImplemented: true },
  { name: 'Image Resizer', slug: 'image-resizer', description: 'Resize images to your desired dimensions.', category: 'image-tools' },
  { name: 'Image Cropper', slug: 'image-cropper', description: 'Crop images to a specific area.', category: 'image-tools' },
  { name: 'Image Rotator', slug: 'image-rotator', description: 'Rotate images by a specified angle.', category: 'image-tools' },
  { name: 'Image Flipper', slug: 'image-flipper', description: 'Flip images horizontally or vertically.', category: 'image-tools' },
  { name: 'Convert JPG to PNG', slug: 'jpg-to-png', description: 'Convert JPG images to PNG format.', category: 'image-tools' },
  { name: 'Convert PNG to JPG', slug: 'png-to-jpg', description: 'Convert PNG images to JPG format.', category: 'image-tools' },
  { name: 'Convert JPG to WebP', slug: 'jpg-to-webp', description: 'Convert JPG images to WebP format.', category: 'image-tools' },
  { name: 'Convert WebP to JPG', slug: 'webp-to-jpg', description: 'Convert WebP images to JPG format.', category: 'image-tools' },
  { name: 'Convert PNG to WebP', slug: 'png-to-webp', description: 'Convert PNG images to WebP format.', category: 'image-tools' },
  { name: 'Convert WebP to PNG', slug: 'webp-to-png', description: 'Convert WebP images to PNG format.', category: 'image-tools' },
  { name: 'HEIC to JPG', slug: 'heic-to-jpg', description: 'Convert HEIC images to JPG format.', category: 'image-tools' },
  { name: 'RAW to JPG', slug: 'raw-to-jpg', description: 'Convert RAW camera images to JPG.', category: 'image-tools' },
  { name: 'BMP to PNG', slug: 'bmp-to-png', description: 'Convert BMP images to PNG format.', category: 'image-tools' },
  { name: 'TIFF to PNG', slug: 'tiff-to-png', description: 'Convert TIFF images to PNG format.', category: 'image-tools' },
  { name: 'ICO (Favicon) Generator', slug: 'ico-generator', description: 'Create an ICO favicon from an image.', category: 'image-tools' },
  { name: 'PNG to ICO', slug: 'png-to-ico', description: 'Convert PNG images to ICO format.', category: 'image-tools' },
  { name: 'SVG to PNG', slug: 'svg-to-png', description: 'Convert SVG vectors to PNG images.', category: 'image-tools' },
  { name: 'PNG to SVG (Vectorize)', slug: 'png-to-svg', description: 'Convert PNG images to SVG vectors.', category: 'image-tools' },
  { name: 'Image to PDF', slug: 'image-to-pdf', description: 'Convert a single image to a PDF file.', category: 'image-tools' },
  { name: 'Multi-Image to Single PDF', slug: 'multi-image-to-pdf', description: 'Combine multiple images into one PDF.', category: 'image-tools' },
  { name: 'Image Watermark Adder', slug: 'image-watermark-adder', description: 'Add a watermark to your images.', category: 'image-tools' },
  { name: 'Image Watermark Remover (inpaint)', slug: 'image-watermark-remover', description: 'Remove watermarks from images.', category: 'image-tools' },
  { name: 'Image Color Picker', slug: 'image-color-picker', description: 'Pick a color from an image.', category: 'image-tools' },
  { name: 'Palette Extractor from Image', slug: 'palette-extractor', description: 'Extract a color palette from an image.', category: 'image-tools' },
  { name: 'Remove Image Noise', slug: 'remove-image-noise', description: 'Reduce noise and grain in images.', category: 'image-tools' },
  { name: 'Sharpen Image', slug: 'sharpen-image', description: 'Sharpen blurry images.', category: 'image-tools' },
  { name: 'Blur Image', slug: 'blur-image', description: 'Apply a blur effect to an image.', category: 'image-tools' },
  { name: 'Pixelate Image', slug: 'pixelate-image', description: 'Pixelate an image for a retro effect.', category: 'image-tools' },
  { name: 'Photo Collage Maker', slug: 'photo-collage-maker', description: 'Create a collage from multiple photos.', category: 'image-tools' },
  { name: 'Meme Generator', slug: 'meme-generator', description: 'Create your own memes easily.', category: 'image-tools' },
  { name: 'Rounded Corners Generator', slug: 'rounded-corners-generator', description: 'Add rounded corners to your images.', category: 'image-tools' },
  { name: 'Image Border/Frame Maker', slug: 'image-border-maker', description: 'Add a border or frame to your images.', category: 'image-tools' },
  { name: 'Image Annotation Tool', slug: 'image-annotation-tool', description: 'Annotate images with text, arrows, and shapes.', category: 'image-tools' },
  { name: 'Transparent PNG Maker', slug: 'transparent-png-maker', description: 'Create a transparent PNG from an image.', category: 'image-tools' },
  { name: 'Image Background Color Changer', slug: 'image-background-color-changer', description: 'Change the background color of an image.', category: 'image-tools' },
  { name: 'Image Upscaler (AI)', slug: 'image-upscaler-ai', description: 'Upscale and enhance images with AI.', category: 'image-tools', isImplemented: true },
  { name: 'Face Retouch (AI)', slug: 'face-retouch-ai', description: 'Retouch faces in photos using AI.', category: 'image-tools', isImplemented: true },
  { name: 'Generative Fill (AI Inpainting)', slug: 'generative-fill-ai', description: 'Use AI to fill in parts of an image.', category: 'image-tools', isImplemented: true },
  { name: 'Image Background Remover (AI)', slug: 'image-background-remover-ai', description: 'Remove backgrounds from images using AI.', category: 'image-tools', isImplemented: true },
  { name: 'Image Watermark Adder (pro variant)', slug: 'image-watermark-adder-pro', description: 'Advanced image watermarking options.', category: 'image-tools' },
  { name: 'Image Noise Reduction (dedicated tool)', slug: 'image-noise-reduction', description: 'Advanced noise reduction for images.', category: 'image-tools' },
  { name: 'Image Rotate & Flip (batch/combined)', slug: 'image-rotate-flip-batch', description: 'Rotate and flip multiple images at once.', category: 'image-tools' },
  { name: 'SVG Optimizer', slug: 'svg-optimizer', description: 'Optimize SVG files for smaller size.', category: 'image-tools' },

  // 3) Document & File Converters
  { name: 'CSV to Excel (XLSX)', slug: 'csv-to-excel', description: 'Convert CSV files to Excel spreadsheets.', category: 'document-file-converters' },
  { name: 'Excel (XLSX) to CSV', slug: 'excel-to-csv', description: 'Convert Excel spreadsheets to CSV files.', category: 'document-file-converters' },
  { name: 'JSON to CSV', slug: 'json-to-csv', description: 'Convert JSON data to CSV format.', category: 'document-file-converters' },
  { name: 'CSV to JSON', slug: 'csv-to-json', description: 'Convert CSV files to JSON format.', category: 'document-file-converters' },
  { name: 'XML to JSON', slug: 'xml-to-json', description: 'Convert XML data to JSON format.', category: 'document-file-converters' },
  { name: 'JSON to XML', slug: 'json-to-xml', description: 'Convert JSON data to XML format.', category: 'document-file-converters' },
  { name: 'YAML to JSON', slug: 'yaml-to-json', description: 'Convert YAML to JSON format.', category: 'document-file-converters' },
  { name: 'JSON to YAML', slug: 'json-to-yaml', description: 'Convert JSON to YAML format.', category: 'document-file-converters' },
  { name: 'Markdown to HTML', slug: 'markdown-to-html', description: 'Convert Markdown to HTML.', category: 'document-file-converters' },
  { name: 'HTML to Markdown', slug: 'html-to-markdown', description: 'Convert HTML to Markdown.', category: 'document-file-converters' },
  { name: 'TXT to CSV', slug: 'txt-to-csv', description: 'Convert plain text to CSV format.', category: 'document-file-converters' },
  { name: 'CSV to TXT', slug: 'csv-to-txt', description: 'Convert CSV to plain text format.', category: 'document-file-converters' },
  { name: 'RTF to DOCX', slug: 'rtf-to-docx', description: 'Convert RTF to DOCX format.', category: 'document-file-converters' },
  { name: 'DOCX to RTF', slug: 'docx-to-rtf', description: 'Convert DOCX to RTF format.', category: 'document-file-converters' },
  { name: 'ODT to DOCX', slug: 'odt-to-docx', description: 'Convert ODT to DOCX format.', category: 'document-file-converters' },
  { name: 'DOCX to ODT', slug: 'docx-to-odt', description: 'Convert DOCX to ODT format.', category: 'document-file-converters' },
  { name: 'LaTeX to PDF', slug: 'latex-to-pdf', description: 'Compile LaTeX code into a PDF.', category: 'document-file-converters' },
  { name: 'PDF to LaTeX', slug: 'pdf-to-latex', description: 'Extract LaTeX from a PDF (experimental).', category: 'document-file-converters' },
  { name: 'EPUB to MOBI', slug: 'epub-to-mobi', description: 'Convert EPUB eBooks to MOBI format.', category: 'document-file-converters' },
  { name: 'MOBI to EPUB', slug: 'mobi-to-epub', description: 'Convert MOBI eBooks to EPUB format.', category: 'document-file-converters' },
  { name: 'HTML Table to CSV', slug: 'html-table-to-csv', description: 'Extract tables from HTML to CSV.', category: 'document-file-converters' },
  { name: 'CSV to HTML Table', slug: 'csv-to-html-table', description: 'Convert CSV data to an HTML table.', category: 'document-file-converters' },
  { name: 'ICS (Calendar) to CSV', slug: 'ics-to-csv', description: 'Convert iCalendar files to CSV.', category: 'document-file-converters' },
  { name: 'CSV to ICS (Calendar)', slug: 'csv-to-ics', description: 'Convert CSV to iCalendar files.', category: 'document-file-converters' },
  { name: 'VCF (Contacts) to CSV', slug: 'vcf-to-csv', description: 'Convert VCF contact files to CSV.', category: 'document-file-converters' },
  { name: 'CSV to VCF', slug: 'csv-to-vcf', description: 'Convert CSV to VCF contact files.', category: 'document-file-converters' },
  { name: 'SRT (Subtitles) to TXT', slug: 'srt-to-txt', description: 'Convert SRT subtitle files to plain text.', category: 'document-file-converters' },
  { name: 'TXT to SRT', slug: 'txt-to-srt', description: 'Create SRT subtitle files from plain text.', category: 'document-file-converters' },
  { name: 'GPX to KML', slug: 'gpx-to-kml', description: 'Convert GPX files to KML format.', category: 'document-file-converters' },
  { name: 'KML to GPX', slug: 'kml-to-gpx', description: 'Convert KML files to GPX format.', category: 'document-file-converters' },
  { name: 'ICS Cleaner', slug: 'ics-cleaner', description: 'Deduplicate events in iCalendar files.', category: 'document-file-converters' },
  { name: 'CSV Dedupe & Merge', slug: 'csv-dedupe-merge', description: 'Deduplicate and merge CSV files.', category: 'document-file-converters' },
  { name: 'Encode/Decode URL List to CSV', slug: 'url-list-to-csv', description: 'Process a list of URLs from/to a CSV.', category: 'document-file-converters' },
  { name: 'Batch File Renamer', slug: 'batch-file-renamer', description: 'Rename multiple files based on rules.', category: 'document-file-converters' },
  { name: 'Case-Sensitive Filename Normalizer', slug: 'filename-normalizer', description: 'Normalize filenames for case sensitivity.', category: 'document-file-converters' },
  { name: 'diacritics Remover (filenames)', slug: 'diacritics-remover-filenames', description: 'Remove diacritics from filenames.', category: 'document-file-converters' },
  { name: 'Unicode Normalizer', slug: 'unicode-normalizer', description: 'Normalize Unicode text (NFC/NFD).', category: 'document-file-converters' },
  { name: 'ZIP to TAR', slug: 'zip-to-tar', description: 'Convert ZIP archives to TAR.', category: 'document-file-converters' },
  { name: 'TAR to ZIP', slug: 'tar-to-zip', description: 'Convert TAR archives to ZIP.', category: 'document-file-converters' },
  { name: '7z to ZIP', slug: '7z-to-zip', description: 'Convert 7z archives to ZIP.', category: 'document-file-converters' },
  { name: 'JSON to Excel (XLSX) Converter', slug: 'json-to-excel', description: 'Convert JSON files to Excel.', category: 'document-file-converters' },
  { name: 'CSV Splitter (standalone)', slug: 'csv-splitter', description: 'Split large CSV files into smaller ones.', category: 'document-file-converters' },

  // 4) Text & Writing Tools
  { name: 'Word Counter', slug: 'word-counter', description: 'Count the number of words in a text.', category: 'text-writing-tools' },
  { name: 'Character Counter', slug: 'character-counter', description: 'Count the number of characters in a text.', category: 'text-writing-tools' },
  { name: 'Sentence Counter', slug: 'sentence-counter', description: 'Count the number of sentences in a text.', category: 'text-writing-tools' },
  { name: 'Reading Time Estimator', slug: 'reading-time-estimator', description: 'Estimate the reading time for a text.', category: 'text-writing-tools' },
  { name: 'Readability Checker', slug: 'readability-checker', description: 'Check the readability of a text (FK, SMOG).', category: 'text-writing-tools' },
  { name: 'Grammar Checker', slug: 'grammar-checker', description: 'Check text for grammatical errors.', category: 'text-writing-tools' },
  { name: 'Spelling Checker', slug: 'spelling-checker', description: 'Check text for spelling mistakes.', category: 'text-writing-tools' },
  { name: 'Punctuation Fixer', slug: 'punctuation-fixer', description: 'Automatically fix punctuation in a text.', category: 'text-writing-tools' },
  { name: 'Case Converter', slug: 'case-converter', description: 'Convert text to different cases (upper, lower, etc.).', category: 'text-writing-tools' },
  { name: 'Remove Extra Spaces', slug: 'remove-extra-spaces', description: 'Remove extra spaces from a text.', category: 'text-writing-tools' },
  { name: 'Remove Line Breaks', slug: 'remove-line-breaks', description: 'Remove line breaks from a text.', category: 'text-writing-tools' },
  { name: 'Sort Lines', slug: 'sort-lines', description: 'Sort lines of text alphabetically.', category: 'text-writing-tools' },
  { name: 'Unique Lines (dedupe)', slug: 'unique-lines', description: 'Remove duplicate lines from a text.', category: 'text-writing-tools' },
  { name: 'Find & Replace', slug: 'find-and-replace', description: 'Find and replace text in bulk.', category: 'text-writing-tools' },
  { name: 'URL Extractor from Text', slug: 'url-extractor', description: 'Extract all URLs from a block of text.', category: 'text-writing-tools' },
  { name: 'Email Extractor from Text', slug: 'email-extractor', description: 'Extract all email addresses from a block of text.', category: 'text-writing-tools' },
  { name: 'Lorem Ipsum Generator', slug: 'lorem-ipsum-generator', description: 'Generate placeholder text.', category: 'text-writing-tools' },
  { name: 'Blog Title Generator', slug: 'blog-title-generator', description: 'Generate blog titles with AI.', category: 'text-writing-tools' },
  { name: 'Meta Description Generator', slug: 'meta-description-generator', description: 'Generate meta descriptions with AI.', category: 'text-writing-tools' },
  { name: 'Paraphraser', slug: 'paraphraser', description: 'Paraphrase text using AI.', category: 'text-writing-tools' },
  { name: 'Summarizer', slug: 'summarizer', description: 'Summarize text using AI.', category: 'text-writing-tools' },
  { name: 'Keyword Extractor', slug: 'keyword-extractor', description: 'Extract keywords from text using NLP.', category: 'text-writing-tools' },
  { name: 'Hashtag Generator', slug: 'hashtag-generator', description: 'Generate hashtags for social media.', category: 'text-writing-tools' },
  { name: 'Slug Generator', slug: 'slug-generator', description: 'Create SEO-friendly URL slugs.', category: 'text-writing-tools' },
  { name: 'Text Diff', slug: 'text-diff', description: 'Compare two texts side-by-side.', category: 'text-writing-tools' },
  { name: 'Markdown Editor', slug: 'markdown-editor', description: 'A what-you-see-is-what-you-get Markdown editor.', category: 'text-writing-tools' },
  { name: 'HTML Entities Encoder/Decoder', slug: 'html-entities-encoder-decoder', description: 'Encode or decode HTML entities.', category: 'text-writing-tools' },
  { name: 'Base64 Text Encoder/Decoder', slug: 'base64-text-encoder-decoder', description: 'Encode or decode text in Base64.', category: 'text-writing-tools' },
  { name: 'ROT13 Encoder/Decoder', slug: 'rot13-encoder-decoder', description: 'Encode or decode text using ROT13.', category: 'text-writing-tools' },
  { name: 'UTM Builder for URLs', slug: 'utm-builder', description: 'Build UTM tracking links for your campaigns.', category: 'text-writing-tools' },
  { name: 'Stopwords Remover', slug: 'stopwords-remover', description: 'Remove common stopwords from text.', category: 'text-writing-tools' },
  { name: 'CamelCase / snake_case Converter', slug: 'case-style-converter', description: 'Convert text between camelCase and snake_case.', category: 'text-writing-tools' },
  { name: 'Accent/Diacritics Remover', slug: 'diacritics-remover', description: 'Remove accents and diacritics from text.', category: 'text-writing-tools' },
  { name: 'JSON Escape/Unescape', slug: 'json-escape-unescape', description: 'Escape or unescape JSON strings.', category: 'text-writing-tools' },
  { name: 'CSV Escape/Unescape', slug: 'csv-escape-unescape', description: 'Escape or unescape CSV strings.', category: 'text-writing-tools' },
  
  // 5) SEO & Website Tools
  { name: 'Domain Availability Checker', slug: 'domain-availability-checker', description: 'Check if a domain name is available.', category: 'seo-website-tools' },
  { name: 'Domain Age Checker', slug: 'domain-age-checker', description: 'Check the age of a domain.', category: 'seo-website-tools' },
  { name: 'WHOIS Lookup', slug: 'whois-lookup', description: 'Look up WHOIS information for a domain.', category: 'seo-website-tools' },
  { name: 'DNS Lookup', slug: 'dns-lookup', description: 'Look up DNS records for a domain.', category: 'seo-website-tools' },
  { name: 'Reverse DNS Lookup', slug: 'reverse-dns-lookup', description: 'Perform a reverse DNS lookup.', category: 'seo-website-tools' },
  { name: 'SSL Certificate Checker', slug: 'ssl-certificate-checker', description: 'Check the SSL certificate of a website.', category: 'seo-website-tools' },
  { name: 'HTTP/2 & HTTPS Status Checker', slug: 'http2-https-checker', description: 'Check if a website supports HTTP/2 and HTTPS.', category: 'seo-website-tools' },
  { name: 'Website Speed Test', slug: 'website-speed-test', description: 'Test the speed of your website.', category: 'seo-website-tools' },
  { name: 'Mobile-Friendly Test', slug: 'mobile-friendly-test', description: 'Test if your website is mobile-friendly.', category: 'seo-website-tools' },
  { name: 'Redirect Chain Checker', slug: 'redirect-chain-checker', description: 'Check for redirect chains on a URL.', category: 'seo-website-tools' },
  { name: 'Broken Link Checker', slug: 'broken-link-checker', description: 'Find broken links on your website.', category: 'seo-website-tools' },
  { name: 'Sitemap Generator (XML)', slug: 'sitemap-generator', description: 'Generate an XML sitemap for your website.', category: 'seo-website-tools' },
  { name: 'Robots.txt Generator', slug: 'robots-txt-generator', description: 'Generate a robots.txt file for your website.', category: 'seo-website-tools' },
  { name: 'Hreflang Generator', slug: 'hreflang-generator', description: 'Generate hreflang tags for your website.', category: 'seo-website-tools' },
  { name: 'Meta Tag Analyzer', slug: 'meta-tag-analyzer', description: 'Analyze the meta tags of a webpage.', category: 'seo-website-tools' },
  { name: 'Open Graph Tag Generator', slug: 'open-graph-generator', description: 'Generate Open Graph tags for your website.', category: 'seo-website-tools' },
  { name: 'Twitter Card Validator', slug: 'twitter-card-validator', description: 'Validate Twitter Card tags for your website.', category: 'seo-website-tools' },
  { name: 'Canonical URL Auditor', slug: 'canonical-url-auditor', description: 'Audit canonical URLs on your website.', category: 'seo-website-tools' },
  { name: 'Keyword Density Checker', slug: 'keyword-density-checker', description: 'Check the keyword density of a webpage.', category: 'seo-website-tools' },
  { name: 'Structured Data (Schema) Tester', slug: 'structured-data-tester', description: 'Test the structured data of a webpage.', category: 'seo-website-tools' },
  { name: 'Favicons & App Manifest Generator', slug: 'favicons-app-manifest-generator', description: 'Generate favicons and an app manifest.', category: 'seo-website-tools' },
  { name: 'Page Size Checker', slug: 'page-size-checker', description: 'Check the size of a webpage.', category: 'seo-website-tools' },
  { name: 'Page Header Analyzer', slug: 'page-header-analyzer', description: 'Analyze the headers of a webpage.', category: 'seo-website-tools' },
  { name: 'Server Status Checker', slug: 'server-status-checker', description: 'Check the status of a web server.', category: 'seo-website-tools' },
  { name: 'Host Location Finder', slug: 'host-location-finder', description: 'Find the location of a web host.', category: 'seo-website-tools' },
  { name: 'Uptime Monitor', slug: 'uptime-monitor', description: 'Monitor the uptime of your website.', category: 'seo-website-tools' },
  { name: 'SERP Snippet Preview', slug: 'serp-snippet-preview', description: 'Preview how your webpage will look in search results.', category: 'seo-website-tools' },
  { name: 'AMP Validator', slug: 'amp-validator', description: 'Validate AMP pages.', category: 'seo-website-tools' },
  { name: 'Core Web Vitals Hints', slug: 'core-web-vitals-hints', description: 'Get hints for improving your Core Web Vitals.', category: 'seo-website-tools' },
  { name: 'Link Extractor', slug: 'link-extractor', description: 'Extract all links from a webpage.', category: 'seo-website-tools' },
  { name: 'XML Sitemap Splitter/Merger', slug: 'xml-sitemap-splitter-merger', description: 'Split or merge XML sitemaps.', category: 'seo-website-tools' },
  { name: 'Nofollow/Follow Link Highlighter', slug: 'link-highlighter', description: 'Highlight nofollow and follow links on a webpage.', category: 'seo-website-tools' },
  { name: 'Heading Structure Analyzer', slug: 'heading-structure-analyzer', description: 'Analyze the heading structure of a webpage.', category: 'seo-website-tools' },
  { name: 'Image ALT Auditor', slug: 'image-alt-auditor', description: 'Audit the ALT text of images on a webpage.', category: 'seo-website-tools' },
  { name: 'Canonical/Duplicate Content Finder', slug: 'duplicate-content-finder', description: 'Find duplicate content on your website.', category: 'seo-website-tools' },

  // 6) Finance & Business Calculators
  { name: 'EMI Calculator', slug: 'emi-calculator', description: 'Calculate Equated Monthly Installments for loans.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Home Loan Eligibility Calculator', slug: 'home-loan-eligibility-calculator', description: 'Check your eligibility for a home loan.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Car Loan EMI Calculator', slug: 'car-loan-emi-calculator', description: 'Calculate EMI for your car loan.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Education Loan EMI Calculator', slug: 'education-loan-emi-calculator', description: 'Calculate EMI for your education loan.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Personal Loan EMI Calculator', slug: 'personal-loan-emi-calculator', description: 'Calculate EMI for your personal loan.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Business Loan EMI Calculator', slug: 'business-loan-emi-calculator', description: 'Calculate EMI for your business loan.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Loan Amortization Schedule', slug: 'loan-amortization-schedule', description: 'View the amortization schedule for your loan.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Compare Loans', slug: 'compare-loans', description: 'Compare two loans side-by-side.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'SIP Calculator', slug: 'sip-calculator', description: 'Calculate the future value for your systematic investment plan.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Lumpsum Investment Calculator', slug: 'lumpsum-investment-calculator', description: 'Calculate the future value of a lumpsum investment.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Mutual Fund Returns Calculator', slug: 'mutual-fund-returns-calculator', description: 'Calculate returns on your mutual fund investments.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'NPS Returns Calculator', slug: 'nps-returns-calculator', description: 'Calculate returns for your National Pension System investment.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'FD Calculator', slug: 'fd-calculator', description: 'Calculate the maturity amount of a Fixed Deposit.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'RD Calculator', slug: 'rd-calculator', description: 'Calculate the maturity amount of a Recurring Deposit.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Compound Interest Calculator', slug: 'compound-interest-calculator', description: 'Calculate compound interest on your investments.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Simple Interest Calculator', slug: 'simple-interest-calculator', description: 'Calculate simple interest on your savings.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'CAGR Calculator', slug: 'cagr-calculator', description: 'Calculate the Compound Annual Growth Rate.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Inflation Adjusted Returns', slug: 'inflation-adjusted-returns', description: 'Calculate the real return on your investments after inflation.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Income Tax Calculator', slug: 'income-tax-calculator', description: 'Calculate your income tax for the financial year.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'HRA Exemption Calculator', slug: 'hra-exemption-calculator', description: 'Calculate your House Rent Allowance exemption.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'GST Calculator', slug: 'gst-calculator', description: 'Calculate the Goods and Services Tax.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'VAT/Sales Tax Calculator', slug: 'vat-sales-tax-calculator', description: 'Calculate Value Added Tax or Sales Tax.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Currency Converter', slug: 'currency-converter', description: 'Convert between different currencies.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Unit Price Calculator', slug: 'unit-price-calculator', description: 'Compare prices of products with different unit sizes.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Discount Calculator', slug: 'discount-calculator', description: 'Calculate the final price after a discount.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Margin & Markup Calculator', slug: 'margin-markup-calculator', description: 'Calculate profit margin and markup.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Break-Even Point Calculator', slug: 'break-even-point-calculator', description: 'Calculate the break-even point for your business.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Profit/Loss Calculator', slug: 'profit-loss-calculator', description: 'Calculate profit or loss on a transaction.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Freelance Hourly Rate Calculator', slug: 'freelance-hourly-rate-calculator', description: 'Determine your hourly rate as a freelancer.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Salary to Hourly Converter', slug: 'salary-to-hourly-converter', description: 'Convert your annual salary to an hourly rate.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Overtime Pay Calculator', slug: 'overtime-pay-calculator', description: 'Calculate your overtime pay.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Retirement Corpus Calculator', slug: 'retirement-corpus-calculator', description: 'Estimate the corpus you need for retirement.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'FIRE Calculator', slug: 'fire-calculator', description: 'Calculate your Financial Independence, Retire Early number.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Gratuity Calculator', slug: 'gratuity-calculator', description: 'Calculate your gratuity amount.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Loan vs. Lease Calculator', slug: 'loan-vs-lease-calculator', description: 'Compare the costs of loaning vs. leasing.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Rent vs. Buy Calculator', slug: 'rent-vs-buy-calculator', description: 'Compare the costs of renting vs. buying a home.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Credit Card Payoff Calculator', slug: 'credit-card-payoff-calculator', description: 'Calculate how long it will take to pay off your credit card.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Mortgage Refinance Savings', slug: 'mortgage-refinance-savings', description: 'Calculate savings from refinancing your mortgage.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Net Worth Tracker', slug: 'net-worth-tracker', description: 'Track your net worth over time.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Budget Planner', slug: 'budget-planner', description: 'Plan your monthly budget.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'GST Calculator (quick mode)', slug: 'gst-calculator-quick', description: 'A faster version of the GST calculator.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Tip Calculator', slug: 'tip-calculator', description: 'A simple tip calculator.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Simple Interest Calculator (quick mode)', slug: 'simple-interest-calculator-quick', description: 'A faster version of the simple interest calculator.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Compound Interest Calculator (quick mode)', slug: 'compound-interest-calculator-quick', description: 'A faster version of the compound interest calculator.', category: 'finance-business-calculators', isImplemented: true },
  { name: 'Age Difference Calculator', slug: 'age-difference-calculator', description: 'Calculate the age difference between two dates.', category: 'finance-business-calculators', isImplemented: true },

  // 7) Math, Science & Academic
  { name: 'Percentage Calculator', slug: 'percentage-calculator', description: 'Calculate percentages.', category: 'math-science-academic', isImplemented: true },
  { name: 'Average/Mean Calculator', slug: 'average-mean-calculator', description: 'Calculate the average of a set of numbers.', category: 'math-science-academic', isImplemented: true },
  { name: 'Median & Mode Calculator', slug: 'median-mode-calculator', description: 'Calculate the median and mode of a set of numbers.', category: 'math-science-academic', isImplemented: true },
  { name: 'Ratio Calculator', slug: 'ratio-calculator', description: 'Calculate ratios.', category: 'math-science-academic', isImplemented: true },
  { name: 'Proportion Calculator', slug: 'proportion-calculator', description: 'Calculate proportions.', category: 'math-science-academic', isImplemented: true },
  { name: 'Standard Deviation Calculator', slug: 'standard-deviation-calculator', description: 'Calculate the standard deviation of a set of numbers.', category: 'math-science-academic', isImplemented: true },
  { name: 'Variance Calculator', slug: 'variance-calculator', description: 'Calculate the variance of a set of numbers.', category: 'math-science-academic', isImplemented: true },
  { name: 'Z-Score Calculator', slug: 'z-score-calculator', description: 'Calculate the z-score of a number.', category: 'math-science-academic', isImplemented: true },
  { name: 'Linear Interpolation Calculator', slug: 'linear-interpolation-calculator', description: 'Perform linear interpolation.', category: 'math-science-academic', isImplemented: true },
  { name: 'Scientific Calculator', slug: 'scientific-calculator', description: 'A full-featured scientific calculator.', category: 'math-science-academic', isImplemented: true },
  { name: 'Quadratic Equation Solver', slug: 'quadratic-equation-solver', description: 'Solve quadratic equations.', category: 'math-science-academic', isImplemented: true },
  { name: 'Matrix Calculator', slug: 'matrix-calculator', description: 'Perform matrix operations (add, multiply, inverse).', category: 'math-science-academic', isImplemented: true },
  { name: 'Determinant Calculator', slug: 'determinant-calculator', description: 'Calculate the determinant of a matrix.', category: 'math-science-academic', isImplemented: true },
  { name: 'Vector Calculator', slug: 'vector-calculator', description: 'Perform vector operations (dot product, cross product).', category: 'math-science-academic', isImplemented: true },
  { name: 'Unit Converter', slug: 'unit-converter', description: 'Convert between different units of measurement.', category: 'math-science-academic', isImplemented: true },
  { name: 'Time Duration Calculator', slug: 'time-duration-calculator', description: 'Calculate the duration between two times.', category: 'math-science-academic', isImplemented: true },
  { name: 'Speed–Distance–Time Calculator', slug: 'speed-distance-time-calculator', description: 'Calculate speed, distance, or time.', category: 'math-science-academic', isImplemented: true },
  { name: 'Density Calculator', slug: 'density-calculator', description: 'Calculate density.', category: 'math-science-academic', isImplemented: true },
  { name: 'BMI Calculator', slug: 'bmi-calculator', description: 'Calculate your Body Mass Index.', category: 'math-science-academic', isImplemented: true },
  { name: 'BMR/TDEE Calculator', slug: 'bmr-tdee-calculator', description: 'Calculate your Basal Metabolic Rate and Total Daily Energy Expenditure.', category: 'math-science-academic', isImplemented: true },
  { name: 'Body Fat % Estimator', slug: 'body-fat-estimator', description: 'Estimate your body fat percentage.', category: 'math-science-academic', isImplemented: true },
  { name: 'Calorie Tracker', slug: 'calorie-tracker', description: 'Track your daily calorie intake.', category: 'math-science-academic', isImplemented: true },
  { name: 'Probability Calculator', slug: 'probability-calculator', description: 'Calculate probabilities.', category: 'math-science-academic', isImplemented: true },
  { name: 'Permutation/Combination Calculator', slug: 'permutation-combination-calculator', description: 'Calculate permutations and combinations.', category: 'math-science-academic', isImplemented: true },
  { name: 'Prime Number Checker', slug: 'prime-number-checker', description: 'Check if a number is prime.', category: 'math-science-academic', isImplemented: true },
  { name: 'Factorization Tool', slug: 'factorization-tool', description: 'Find the prime factors of a number.', category: 'math-science-academic', isImplemented: true },
  { name: 'LCM & GCD Calculator', slug: 'lcm-gcd-calculator', description: 'Calculate the Least Common Multiple and Greatest Common Divisor.', category: 'math-science-academic', isImplemented: true },
  { name: 'Roman Numeral Converter', slug: 'roman-numeral-converter', description: 'Convert numbers to Roman numerals.', category: 'math-science-academic', isImplemented: true },
  { name: 'Base Converter', slug: 'base-converter', description: 'Convert numbers between different bases.', category: 'math-science-academic', isImplemented: true },
  { name: 'Significant Figures Calculator', slug: 'significant-figures-calculator', description: 'Calculate significant figures.', category: 'math-science-academic', isImplemented: true },
  { name: 'Percentage Change/Difference', slug: 'percentage-change-difference', description: 'Calculate percentage change or difference.', category: 'math-science-academic', isImplemented: true },
  { name: 'Exponent/Power Calculator', slug: 'exponent-power-calculator', description: 'Calculate exponents and powers.', category: 'math-science-academic', isImplemented: true },
  { name: 'Logarithm Calculator', slug: 'logarithm-calculator', description: 'Calculate logarithms.', category: 'math-science-academic', isImplemented: true },
  { name: 'Angle Converter', slug: 'angle-converter', description: 'Convert angles between degrees, radians, and grads.', category: 'math-science-academic', isImplemented: true },
  { name: 'Scientific Notation Converter', slug: 'scientific-notation-converter', description: 'Convert numbers to scientific notation.', category: 'math-science-academic', isImplemented: true },
  { name: 'BMR Calculator', slug: 'bmr-calculator', description: 'Calculate your Basal Metabolic Rate.', category: 'math-science-academic', isImplemented: true },

  // 8) Data & Developer Utilities
  { name: 'JSON Formatter/Beautifier', slug: 'json-formatter', description: 'Format and beautify JSON data.', category: 'data-developer-utilities' },
  { name: 'JSON Validator', slug: 'json-validator', description: 'Validate JSON data.', category: 'data-developer-utilities' },
  { name: 'JSON Minifier', slug: 'json-minifier', description: 'Minify JSON data.', category: 'data-developer-utilities' },
  { name: 'XML Formatter/Beautifier', slug: 'xml-formatter', description: 'Format and beautify XML data.', category: 'data-developer-utilities' },
  { name: 'XML Validator', slug: 'xml-validator', description: 'Validate XML data.', category: 'data-developer-utilities' },
  { name: 'XML Minifier', slug: 'xml-minifier', description: 'Minify XML data.', category: 'data-developer-utilities' },
  { name: 'HTML Minifier', slug: 'html-minifier', description: 'Minify HTML code.', category: 'data-developer-utilities' },
  { name: 'CSS Minifier', slug: 'css-minifier', description: 'Minify CSS code.', category: 'data-developer-utilities' },
  { name: 'JS Minifier/Uglifier', slug: 'js-minifier', description: 'Minify and uglify JavaScript code.', category: 'data-developer-utilities' },
  { name: 'SQL Formatter/Beautifier', slug: 'sql-formatter', description: 'Format and beautify SQL code.', category: 'data-developer-utilities' },
  { name: 'YAML Formatter', slug: 'yaml-formatter', description: 'Format YAML data.', category: 'data-developer-utilities' },
  { name: 'TOML Formatter', slug: 'toml-formatter', description: 'Format TOML data.', category: 'data-developer-utilities' },
  { name: 'CSV Validator', slug: 'csv-validator', description: 'Validate CSV files.', category: 'data-developer-utilities' },
  { name: 'UUID Generator', slug: 'uuid-generator', description: 'Generate UUIDs (v1/v4).', category: 'data-developer-utilities' },
  { name: 'NanoID Generator', slug: 'nanoid-generator', description: 'Generate NanoIDs.', category: 'data-developer-utilities' },
  { name: 'Slugify Tool', slug: 'slugify-tool', description: 'Create URL-friendly slugs from text.', category: 'data-developer-utilities' },
  { name: 'URL Encoder/Decoder', slug: 'url-encoder-decoder', description: 'Encode or decode URLs.', category: 'data-developer-utilities' },
  { name: 'Base64 Encoder/Decoder', slug: 'base64-encoder-decoder', description: 'Encode or decode data in Base64.', category: 'data-developer-utilities' },
  { name: 'Hash Generator', slug: 'hash-generator', description: 'Generate hashes (MD5, SHA-1, SHA-256).', category: 'data-developer-utilities' },
  { name: 'HMAC Generator', slug: 'hmac-generator', description: 'Generate HMACs.', category: 'data-developer-utilities' },
  { name: 'JWT Decoder', slug: 'jwt-decoder', description: 'Decode JSON Web Tokens.', category: 'data-developer-utilities' },
  { name: 'Regex Tester', slug: 'regex-tester', description: 'Test regular expressions.', category: 'data-developer-utilities' },
  { name: 'Diff Tool', slug: 'diff-tool', description: 'Compare two texts or code snippets.', category: 'data-developer-utilities' },
  { name: 'Prettify Code', slug: 'prettify-code', description: 'Prettify code in various languages.', category: 'data-developer-utilities' },
  { name: 'Colorize Code Blocks', slug: 'colorize-code-blocks', description: 'Colorize code blocks for HTML display.', category: 'data-developer-utilities' },
  { name: 'JSONPath Tester', slug: 'jsonpath-tester', description: 'Test JSONPath expressions.', category: 'data-developer-utilities' },
  { name: 'XPath Tester', slug: 'xpath-tester', description: 'Test XPath expressions.', category: 'data-developer-utilities' },
  { name: 'GraphQL Query Beautifier', slug: 'graphql-query-beautifier', description: 'Beautify GraphQL queries.', category: 'data-developer-utilities' },
  { name: 'CSV Splitter/Merger', slug: 'csv-splitter-merger', description: 'Split or merge CSV files.', category: 'data-developer-utilities' },
  { name: 'Large File Chunker', slug: 'large-file-chunker', description: 'Chunk large files on the client-side.', category: 'data-developer-utilities' },
  { name: 'Hex Dump Viewer', slug: 'hex-dump-viewer', description: 'View the hex dump of a file.', category: 'data-developer-utilities' },
  { name: 'Binary Viewer', slug: 'binary-viewer', description: 'View files in binary format.', category: 'data-developer-utilities' },
  { name: 'Unix Timestamp Converter', slug: 'unix-timestamp-converter', description: 'Convert Unix timestamps to human-readable dates.', category: 'data-developer-utilities' },
  { name: 'Cron Expression Generator', slug: 'cron-expression-generator', description: 'Generate cron expressions.', category: 'data-developer-utilities' },
  { name: 'Cron Expression Parser/Next Run', slug: 'cron-expression-parser', description: 'Parse cron expressions and find the next run time.', category: 'data-developer-utilities' },
  { name: 'URL Shortener', slug: 'url-shortener', description: 'Shorten long URLs.', category: 'data-developer-utilities' },
  { name: 'URL Expander', slug: 'url-expander', description: 'Expand shortened URLs.', category: 'data-developer-utilities' },
  { name: 'Open Redirect Checker', slug: 'open-redirect-checker', description: 'Check for open redirect vulnerabilities.', category: 'data-developer-utilities' },
  { name: 'Link Health Checker', slug: 'link-health-checker', description: 'Check the health of a list of links.', category: 'data-developer-utilities' },

  // 9) Web & URL Utilities
  { name: 'Bulk Status Code Checker', slug: 'bulk-status-code-checker', description: 'Check the status code of multiple URLs.', category: 'web-url-utilities' },
  { name: 'HTTP Header Viewer', slug: 'http-header-viewer', description: 'View the HTTP headers of a URL.', category: 'web-url-utilities' },
  { name: 'CORS Tester', slug: 'cors-tester', description: 'Test Cross-Origin Resource Sharing.', category: 'web-url-utilities' },
  { name: 'Content-Type Sniffer', slug: 'content-type-sniffer', description: 'Sniff the content type of a URL.', category: 'web-url-utilities' },
  { name: 'HTML Screenshot', slug: 'html-screenshot', description: 'Take a screenshot of a webpage.', category: 'web-url-utilities' },
  { name: 'QR Code Generator', slug: 'qr-code-generator', description: 'Generate QR codes.', category: 'web-url-utilities' },
  { name: 'QR Code Reader', slug: 'qr-code-reader', description: 'Read QR codes from an image or webcam.', category: 'web-url-utilities' },
  { name: 'Barcode Generator', slug: 'barcode-generator', description: 'Generate barcodes (EAN, UPC, Code128).', category: 'web-url-utilities' },
  { name: 'Bulk QR Generator', slug: 'bulk-qr-generator', description: 'Generate QR codes in bulk from a CSV.', category: 'web-url-utilities' },
  { name: 'Sitemap URL Pinger', slug: 'sitemap-url-pinger', description: 'Ping search engines with your sitemap URL.', category: 'web-url-utilities' },
  { name: 'URL Canonicalizer', slug: 'url-canonicalizer', description: 'Canonicalize URLs.', category: 'web-url-utilities' },
  { name: 'URL Normalizer', slug: 'url-normalizer', description: 'Normalize URLs by stripping parameters.', category: 'web-url-utilities' },
  { name: 'Robots.txt Tester', slug: 'robots-txt-tester', description: 'Test your robots.txt file.', category: 'web-url-utilities' },
  { name: 'Disallow/Allow Rule Helper', slug: 'disallow-allow-rule-helper', description: 'Helper for creating disallow/allow rules in robots.txt.', category: 'web-url-utilities' },
  { name: 'Cookie Parser', slug: 'cookie-parser', description: 'Parse document.cookie strings.', category: 'web-url-utilities' },
  { name: 'Referrer Policy Tester', slug: 'referrer-policy-tester', description: 'Test referrer policies.', category: 'web-url-utilities' },
  { name: 'CSP Builder', slug: 'csp-builder', description: 'Build Content Security Policies.', category: 'web-url-utilities' },
  { name: 'HSTS Preload Check', slug: 'hsts-preload-check', description: 'Check HSTS preload status.', category: 'web-url-utilities' },
  { name: 'Mixed Content Checker', slug: 'mixed-content-checker', description: 'Check for mixed content on a webpage.', category: 'web-url-utilities' },
  { name: 'Link Preview Fetch', slug: 'link-preview-fetch', description: 'Fetch link previews (Open Graph).', category: 'web-url-utilities' },
  { name: 'HTML to Clean Text', slug: 'html-to-clean-text', description: 'Convert HTML to clean text.', category: 'web-url-utilities' },
  { name: 'Microdata/RDFa Extractor', slug: 'microdata-rdfa-extractor', description: 'Extract Microdata and RDFa from a webpage.', category: 'web-url-utilities' },
  { name: 'Social Share Link Builder', slug: 'social-share-link-builder', description: 'Build social share links.', category: 'web-url-utilities' },
  { name: 'Deep-Link Generator', slug: 'deep-link-generator', description: 'Generate deep links for apps.', category: 'web-url-utilities' },
  { name: 'URL Safe Filename Maker', slug: 'url-safe-filename-maker', description: 'Create URL-safe filenames.', category: 'web-url-utilities' },
  { name: 'QR Code Generator (with Logo)', slug: 'qr-code-generator-with-logo', description: 'Generate QR codes with a logo.', category: 'web-url-utilities' },
  { name: 'URL Expander/Shortener (combined)', slug: 'url-expander-shortener', description: 'A combined tool for expanding and shortening URLs.', category: 'web-url-utilities' },
  { name: 'Password Generator', slug: 'password-generator', description: 'Generate strong, random passwords.', category: 'web-url-utilities' },
  { name: 'Passphrase Generator', slug: 'passphrase-generator', description: 'Generate memorable passphrases.', category: 'web-url-utilities' },
  { name: 'Password Strength Checker', slug: 'password-strength-checker', description: 'Check the strength of your passwords.', category: 'web-url-utilities' },

  // 10) Security, Privacy & Hashing
  { name: 'Have I Been Pwned Email Checker', slug: 'have-i-been-pwned-checker', description: 'Check if your email has been compromised in a data breach.', category: 'security-privacy-hashing' },
  { name: 'Salt Generator', slug: 'salt-generator', description: 'Generate random salts for hashing.', category: 'security-privacy-hashing' },
  { name: 'Hash File', slug: 'hash-file', description: 'Generate hashes for files (MD5, SHA-1, SHA-256).', category: 'security-privacy-hashing' },
  { name: 'Verify File Checksum', slug: 'verify-file-checksum', description: 'Verify the checksum of a file.', category: 'security-privacy-hashing' },
  { name: 'PGP Key Generator', slug: 'pgp-key-generator', description: 'Generate PGP keys.', category: 'security-privacy-hashing' },
  { name: 'PGP Encrypt/Decrypt', slug: 'pgp-encrypt-decrypt', description: 'Encrypt or decrypt messages with PGP.', category: 'security-privacy-hashing' },
  { name: 'AES Encrypt/Decrypt', slug: 'aes-encrypt-decrypt', description: 'Encrypt or decrypt data with AES.', category: 'security-privacy-hashing' },
  { name: 'RSA Keypair Generator', slug: 'rsa-keypair-generator', description: 'Generate RSA keypairs.', category: 'security-privacy-hashing' },
  { name: 'RSA Encrypt/Decrypt', slug: 'rsa-encrypt-decrypt', description: 'Encrypt or decrypt data with RSA.', category: 'security-privacy-hashing' },
  { name: 'String Obfuscator', slug: 'string-obfuscator', description: 'Obfuscate strings.', category: 'security-privacy-hashing' },
  { name: 'Email Address Masker', slug: 'email-address-masker', description: 'Mask email addresses.', category: 'security-privacy-hashing' },
  { name: 'Redact Sensitive Data', slug: 'redact-sensitive-data', description: 'Redact sensitive data from text.', category: 'security-privacy-hashing' },
  { name: 'Privacy Policy Generator', slug: 'privacy-policy-generator', description: 'Generate a privacy policy for your website.', category: 'security-privacy-hashing' },
  { name: 'Cookie Consent Generator', slug: 'cookie-consent-generator', description: 'Generate a cookie consent banner.', category: 'security-privacy-hashing' },
  { name: 'DPI-Aware QR', slug: 'dpi-aware-qr', description: 'Generate high-error-correction QR codes.', category: 'security-privacy-hashing' },
  { name: 'Secure Note', slug: 'secure-note', description: 'Create temporary, client-side secure notes.', category: 'security-privacy-hashing' },
  { name: 'Disposable Link Generator', slug: 'disposable-link-generator', description: 'Generate time-bound disposable links.', category: 'security-privacy-hashing' },
  { name: 'IP Anonymizer', slug: 'ip-anonymizer', description: 'Anonymize IP addresses in logs.', category: 'security-privacy-hashing' },
  { name: 'Do Not Track Tester', slug: 'do-not-track-tester', description: 'Test Do Not Track settings.', category: 'security-privacy-hashing' },
  { name: 'CSP Violations Logger', slug: 'csp-violations-logger', description: 'Guide for logging CSP violations.', category: 'security-privacy-hashing' },
  { name: 'Passwordless Magic Link Builder', slug: 'magic-link-builder', description: 'Demo for building passwordless magic links.', category: 'security-privacy-hashing' },
  { name: 'Two-Factor Code Generator', slug: 'two-factor-code-generator', description: 'Demo for generating TOTP codes.', category: 'security-privacy-hashing' },
  { name: 'Security Headers Score', slug: 'security-headers-score', description: 'Helper for scoring security headers.', category: 'security-privacy-hashing' },
  { name: 'Robots Honeypot Link Builder', slug: 'robots-honeypot-link-builder', description: 'Build honeypot links for your robots.txt.', category: 'security-privacy-hashing' },
  { name: 'Email Address Encoder', slug: 'email-address-encoder', description: 'Encode email addresses to prevent scraping.', category: 'security-privacy-hashing' },
  { name: 'Form Input Sanitizer', slug: 'form-input-sanitizer', description: 'Sample for sanitizing form inputs.', category: 'security-privacy-hashing' },
  { name: 'Secret Sharing', slug: 'secret-sharing', description: 'Demo for Shamir\'s Secret Sharing.', category: 'security-privacy-hashing' },
  { name: 'Password Generator (Advanced)', slug: 'password-generator-advanced', description: 'Advanced password generation options.', category: 'security-privacy-hashing' },
  { name: 'Daily Planner Generator', slug: 'daily-planner-generator', description: 'Generate a daily planner.', category: 'security-privacy-hashing' },
  { name: 'To-Do List', slug: 'to-do-list', description: 'A lightweight to-do list.', category: 'security-privacy-hashing' },
  
  // 11) Productivity & Planning
  { name: 'Pomodoro Timer', slug: 'pomodoro-timer', description: 'A timer for the Pomodoro Technique.', category: 'productivity-planning', isImplemented: true },
  { name: 'Habit Tracker', slug: 'habit-tracker', description: 'Track your daily habits.', category: 'productivity-planning', isImplemented: true },
  { name: 'Goal Tracker', slug: 'goal-tracker', description: 'Track your long-term goals.', category: 'productivity-planning', isImplemented: true },
  { name: 'Eisenhower Matrix Tool', slug: 'eisenhower-matrix-tool', description: 'Organize your tasks using the Eisenhower Matrix.', category: 'productivity-planning', isImplemented: true },
  { name: 'Kanban Board', slug: 'kanban-board', description: 'A lightweight Kanban board.', category: 'productivity-planning', isImplemented: true },
  { name: 'Meeting Agenda Generator', slug: 'meeting-agenda-generator', description: 'Generate agendas for your meetings.', category: 'productivity-planning', isImplemented: true },
  { name: 'Meeting Minutes Template', slug: 'meeting-minutes-template', description: 'A template for taking meeting minutes.', category: 'productivity-planning', isImplemented: true },
  { name: 'Time Zone Converter', slug: 'time-zone-converter', description: 'Convert between different time zones.', category: 'productivity-planning', isImplemented: true },
  { name: 'World Clock Board', slug: 'world-clock-board', description: 'A world clock board.', category: 'productivity-planning', isImplemented: true },
  { name: 'Calendar Event Builder', slug: 'calendar-event-builder', description: 'Build calendar events (ICS).', category: 'productivity-planning', isImplemented: true },
  { name: 'Birthday Reminder', slug: 'birthday-reminder', description: 'A local birthday reminder.', category: 'productivity-planning', isImplemented: true },
  { name: 'Random Name Picker', slug: 'random-name-picker', description: 'Pick a random name from a list.', category: 'productivity-planning', isImplemented: true },
  { name: 'Seating Chart Generator', slug: 'seating-chart-generator', description: 'Generate seating charts.', category: 'productivity-planning', isImplemented: true },
  { name: 'Checklist Maker', slug: 'checklist-maker', description: 'Create checklists.', category: 'productivity-planning', isImplemented: true },
  { name: 'Decision Coin/Spinner', slug: 'decision-coin-spinner', description: 'A coin flipper and spinner for making decisions.', category: 'productivity-planning', isImplemented: true },
  { name: 'Mind Map', slug: 'mind-map', description: 'A basic mind mapping tool.', category: 'productivity-planning', isImplemented: true },
  { name: 'Notes Markdown Pad', slug: 'notes-markdown-pad', description: 'A Markdown pad for taking notes.', category: 'productivity-planning', isImplemented: true },
  { name: 'Sticky Notes Board', slug: 'sticky-notes-board', description: 'A virtual sticky notes board.', category: 'productivity-planning', isImplemented: true },
  { name: 'Focus Noise', slug: 'focus-noise', description: 'Textual prompts for focus noise.', category: 'productivity-planning', isImplemented: true },
  { name: 'Break Reminder', slug: 'break-reminder', description: 'A reminder to take breaks.', category: 'productivity-planning', isImplemented: true },
  { name: 'Travel Packing List Generator', slug: 'travel-packing-list-generator', description: 'Generate a packing list for your travels.', category: 'productivity-planning', isImplemented: true },
  { name: 'Shopping List Maker', slug: 'shopping-list-maker', description: 'Create a shopping list.', category: 'productivity-planning', isImplemented: true },
  { name: 'Invoice Generator', slug: 'invoice-generator', description: 'Generate simple invoices.', category: 'productivity-planning', isImplemented: true },
  { name: 'Quote/Estimate Builder', slug: 'quote-estimate-builder', description: 'Build quotes and estimates.', category: 'productivity-planning', isImplemented: true },
  { name: 'Expense Splitter', slug: 'expense-splitter', description: 'Split expenses with friends.', category: 'productivity-planning', isImplemented: true },
  { name: 'Tip Calculator', slug: 'tip-calculator', description: 'A simple tip calculator.', category: 'productivity-planning', isImplemented: true },
  { name: 'Simple CRM Contacts', slug: 'simple-crm-contacts', description: 'A simple CRM for managing contacts locally.', category: 'productivity-planning', isImplemented: true },
  { name: 'Lead Capture Form Builder', slug: 'lead-capture-form-builder', description: 'Build lead capture forms.', category: 'productivity-planning', isImplemented: true },
  { name: 'Step Counter (Manual Input)', slug: 'step-counter', description: 'Manually input your daily steps.', category: 'productivity-planning', isImplemented: true },
  { name: 'Typing Speed Test', slug: 'typing-speed-test', description: 'Test your typing speed.', category: 'productivity-planning', isImplemented: true },
  
  // 12) Networking & Diagnostics
  { name: 'Ping Test', slug: 'ping-test', description: 'Test the reachability of a host.', category: 'networking-diagnostics' },
  { name: 'Traceroute Visualizer', slug: 'traceroute-visualizer', description: 'Visualize the path of packets across a network.', category: 'networking-diagnostics' },
  { name: 'Port Scanner', slug: 'port-scanner', description: 'Scan for open ports on a host.', category: 'networking-diagnostics' },
  { name: 'IP Geolocation Lookup', slug: 'ip-geolocation-lookup', description: 'Look up the geolocation of an IP address.', category: 'networking-diagnostics' },
  { name: 'ASN Lookup', slug: 'asn-lookup', description: 'Look up Autonomous System Numbers.', category: 'networking-diagnostics' },
  { name: 'BGP Prefix Lookup', slug: 'bgp-prefix-lookup', description: 'Look up BGP prefixes.', category: 'networking-diagnostics' },
  { name: 'CDN Finder', slug: 'cdn-finder', description: 'Find the CDN used by a website.', category: 'networking-diagnostics' },
  { name: 'DNS Propagation Checker', slug: 'dns-propagation-checker', description: 'Check DNS propagation across the globe.', category: 'networking-diagnostics' },
  { name: 'MX Record Tester', slug: 'mx-record-tester', description: 'Test MX records for a domain.', category: 'networking-diagnostics' },
  { name: 'SPF/DMARC Analyzer', slug: 'spf-dmarc-analyzer', description: 'Analyze SPF and DMARC records.', category: 'networking-diagnostics' },
  { name: 'DKIM Record Checker', slug: 'dkim-record-checker', description: 'Check DKIM records for a domain.', category: 'networking-diagnostics' },
  { name: 'HTTP/HTTPS Redirect Tester', slug: 'http-https-redirect-tester', description: 'Test HTTP/HTTPS redirects.', category: 'networking-diagnostics' },
  { name: 'TLS Version & Cipher Checker', slug: 'tls-version-cipher-checker', description: 'Check TLS versions and cipher suites.', category: 'networking-diagnostics' },
  { name: 'IPv4/IPv6 Compatibility Test', slug: 'ipv4-ipv6-compatibility-test', description: 'Test for IPv4/IPv6 compatibility.', category: 'networking-diagnostics' },
  { name: 'WebSocket Echo Tester', slug: 'websocket-echo-tester', description: 'Test WebSocket connections.', category: 'networking-diagnostics' },
  { name: 'gZIP/Brotli Compression Checker', slug: 'gzip-brotli-compression-checker', description: 'Check for gZIP/Brotli compression.', category: 'networking-diagnostics' },
  { name: 'Content-Length Estimator', slug: 'content-length-estimator', description: 'Estimate the content length of a resource.', category: 'networking-diagnostics' },
  { name: 'Cache-Control Analyzer', slug: 'cache-control-analyzer', description: 'Analyze Cache-Control headers.', category: 'networking-diagnostics' },
  { name: 'ETag/Last-Modified Checker', slug: 'etag-last-modified-checker', description: 'Check ETag and Last-Modified headers.', category: 'networking-diagnostics' },
  { name: 'Hotlink Protection Tester', slug: 'hotlink-protection-tester', description: 'Test hotlink protection.', category: 'networking-diagnostics' },
  { name: 'CNAME Flattening Checker', slug: 'cname-flattening-checker', description: 'Check for CNAME flattening.', category: 'networking-diagnostics' },
  { name: 'AAAA (IPv6) Readiness Checker', slug: 'aaaa-readiness-checker', description: 'Check for AAAA (IPv6) readiness.', category: 'networking-diagnostics' },
  { name: 'Public IP Reveal', slug: 'public-ip-reveal', description: 'Reveal your public IP address.', category: 'networking-diagnostics' },
  { name: 'NAT Type Guess', slug: 'nat-type-guess', description: 'Guess your NAT type.', category: 'networking-diagnostics' },
  { name: 'DNS over HTTPS Test', slug: 'dns-over-https-test', description: 'Test for DNS over HTTPS.', category: 'networking-diagnostics' },

  // 13) Color, Design & Branding
  { name: 'IP Location Finder (end-user friendly wrapper)', slug: 'ip-location-finder', description: 'Find the location of an IP address.', category: 'color-design-branding' },
  { name: 'Color Picker (HEX/RGB/HSL)', slug: 'color-picker', description: 'Pick colors and get their values in HEX, RGB, and HSL.', category: 'color-design-branding' },
  { name: 'Contrast Checker (WCAG)', slug: 'contrast-checker', description: 'Check color contrast for WCAG compliance.', category: 'color-design-branding' },
  { name: 'Palette Generator from Image', slug: 'palette-generator-from-image', description: 'Generate a color palette from an image.', category: 'color-design-branding' },
  { name: 'Palette Harmonies', slug: 'palette-harmonies', description: 'Generate color harmonies (monochromatic, triadic, etc.).', category: 'color-design-branding' },
  { name: 'Gradient Generator', slug: 'gradient-generator', description: 'Generate CSS gradients.', category: 'color-design-branding' },
  { name: 'Glassmorphism Generator', slug: 'glassmorphism-generator', description: 'Generate CSS for the glassmorphism effect.', category: 'color-design-branding' },
  { name: 'Neumorphism Generator', slug: 'neumorphism-generator', description: 'Generate CSS for the neumorphism effect.', category: 'color-design-branding' },
  { name: 'Shadow Generator', slug: 'shadow-generator', description: 'Generate CSS for box and text shadows.', category: 'color-design-branding' },
  { name: 'Border-Radius Visualizer', slug: 'border-radius-visualizer', description: 'Visualize and generate CSS for border-radius.', category: 'color-design-branding' },
  { name: 'CSS Clip-Path Maker', slug: 'css-clip-path-maker', description: 'Create CSS clip-paths.', category: 'color-design-branding' },
  { name: 'SVG Wave/Blob Generator', slug: 'svg-wave-blob-generator', description: 'Generate SVG waves and blobs.', category: 'color-design-branding' },
  { name: 'Favicon Generator (ICO/PNG)', slug: 'favicon-generator', description: 'Generate favicons in ICO and PNG formats.', category: 'color-design-branding' },
  { name: 'App Icon Generator', slug: 'app-icon-generator', description: 'Generate app icons for iOS and Android.', category: 'color-design-branding' },
  { name: 'Social Media Banner Resizer', slug: 'social-media-banner-resizer', description: 'Resize banners for social media.', category: 'color-design-branding' },
  { name: 'Logo Sketch Pad', slug: 'logo-sketch-pad', description: 'A basic sketch pad for logo ideas.', category: 'color-design-branding' },
  { name: 'Brand Style Guide Starter', slug: 'brand-style-guide-starter', description: 'A starter template for brand style guides.', category: 'color-design-branding' },
  { name: 'Font Pairing Suggestions', slug: 'font-pairing-suggestions', description: 'Get suggestions for font pairings.', category: 'color-design-branding' },
  { name: 'Webfont Converter', slug: 'webfont-converter', description: 'Convert fonts to webfont formats (TTF, WOFF, WOFF2).', category: 'color-design-branding' },
  { name: 'Placeholder Image Generator', slug: 'placeholder-image-generator', description: 'Generate placeholder images.', category: 'color-design-branding' },
  { name: 'Placeholder Text/Avatar Generator', slug: 'placeholder-text-avatar-generator', description: 'Generate placeholder text and avatars.', category: 'color-design-branding' },
  { name: 'Wireframe Blocks Library', slug: 'wireframe-blocks-library', description: 'A library of wireframe blocks.', category: 'color-design-branding' },
  { name: 'UI Component Shadow Tokens', slug: 'ui-component-shadow-tokens', description: 'Generate shadow tokens for UI components.', category: 'color-design-branding' },
  { name: 'CSS Variable Palette Exporter', slug: 'css-variable-palette-exporter', description: 'Export color palettes as CSS variables.', category: 'color-design-branding' },
  { name: 'Accessibility Landmarks Checker', slug: 'accessibility-landmarks-checker', description: 'Check for accessibility landmarks.', category: 'color-design-branding' },

  // 14) OCR, Language & Localization
  { name: 'Printable QR Poster Creator', slug: 'printable-qr-poster-creator', description: 'Create printable QR posters.', category: 'ocr-language-localization' },
  { name: 'Image to Text (OCR)', slug: 'image-to-text-ocr', description: 'Extract text from images using OCR.', category: 'ocr-language-localization' },
  { name: 'PDF to Text (OCR)', slug: 'pdf-to-text-ocr', description: 'Extract text from PDFs using OCR.', category: 'ocr-language-localization' },
  { name: 'Handwriting OCR', slug: 'handwriting-ocr', description: 'Extract text from handwritten notes.', category: 'ocr-language-localization' },
  { name: 'Table OCR', slug: 'table-ocr', description: 'Extract tables from images and PDFs.', category: 'ocr-language-localization' },
  { name: 'Math OCR', slug: 'math-ocr', description: 'Extract mathematical equations from images.', category: 'ocr-language-localization' },
  { name: 'Business Card OCR to VCF', slug: 'business-card-ocr-to-vcf', description: 'Convert business cards to VCF files.', category: 'ocr-language-localization' },
  { name: 'Passport/MRZ Reader', slug: 'passport-mrz-reader', description: 'Read Machine-Readable Zones from passports.', category: 'ocr-language-localization' },
  { name: 'ID Card OCR Redactor', slug: 'id-card-ocr-redactor', description: 'Redact sensitive information from ID cards.', category: 'ocr-language-localization' },
  { name: 'Language Detector', slug: 'language-detector', description: 'Detect the language of a text.', category: 'ocr-language-localization' },
  { name: 'Transliteration Tool', slug: 'transliteration-tool', description: 'Transliterate text between different scripts.', category: 'ocr-language-localization' },
  { name: 'Slugify International Characters', slug: 'slugify-international-characters', description: 'Slugify international characters.', category: 'ocr-language-localization' },
  { name: 'Plurals & Inflections Helper', slug: 'plurals-inflections-helper', description: 'A helper for plurals and inflections.', category: 'ocr-language-localization' },
  { name: 'Spell-Out Numbers', slug: 'spell-out-numbers', description: 'Spell out numbers in different languages.', category: 'ocr-language-localization' },
  { name: 'Number-to-Words Converter', slug: 'number-to-words-converter', description: 'Convert numbers to words.', category: 'ocr-language-localization' },
  { name: 'Words-to-Number Converter', slug: 'words-to-number-converter', description: 'Convert words to numbers.', category: 'ocr-language-localization' },
  { name: 'Date Localization Formatter', slug: 'date-localization-formatter', description: 'Format dates for different locales.', category: 'ocr-language-localization' },
  { name: 'Currency Localization Formatter', slug: 'currency-localization-formatter', description: 'Format currency for different locales.', category: 'ocr-language-localization' },
  { name: 'Right-to-Left Layout Tester', slug: 'right-to-left-layout-tester', description: 'Test right-to-left layouts.', category: 'ocr-language-localization' },
  { name: 'Punycode Converter', slug: 'punycode-converter', description: 'Convert between Punycode and Unicode.', category: 'ocr-language-localization' },
  { name: 'Unicode Grapheme Splitter', slug: 'unicode-grapheme-splitter', description: 'Split Unicode graphemes.', category: 'ocr-language-localization' },
  { name: 'Emoji Stripper/Normalizer', slug: 'emoji-stripper-normalizer', description: 'Strip or normalize emojis.', category: 'ocr-language-localization' },
  { name: 'Regex Accent-Insensitive Helper', slug: 'regex-accent-insensitive-helper', description: 'A helper for accent-insensitive regex.', category: 'ocr-language-localization' },
  { name: 'ICU Message Previewer', slug: 'icu-message-previewer', description: 'Preview ICU messages.', category: 'ocr-language-localization' },
  { name: 'CSV Language Columns Merger', slug: 'csv-language-columns-merger', description: 'Merge language columns in a CSV.', category: 'ocr-language-localization' },
  
  // 15) System & File Management
  { name: 'Subtitle Language Mapper', slug: 'subtitle-language-mapper', description: 'Map subtitle languages.', category: 'system-file-management' },
  { name: 'ZIP Archive Creator', slug: 'zip-archive-creator', description: 'Create ZIP archives.', category: 'system-file-management' },
  { name: 'Unzip Files', slug: 'unzip-files', description: 'Unzip files from an archive.', category: 'system-file-management' },
  { name: 'TAR/GZ Creator', slug: 'tar-gz-creator', description: 'Create TAR/GZ archives.', category: 'system-file-management' },
  { name: 'Untar/UnGzip', slug: 'untar-ungzip', description: 'Untar/UnGzip files from an archive.', category: 'system-file-management' },
  { name: '7z Extractor', slug: '7z-extractor', description: 'Extract files from a 7z archive.', category: 'system-file-management' },
  { name: 'File Splitter', slug: 'file-splitter', description: 'Split files by size.', category: 'system-file-management' },
  { name: 'File Joiner', slug: 'file-joiner', description: 'Join split files.', category: 'system-file-management' },
  { name: 'File Integrity Verifier', slug: 'file-integrity-verifier', description: 'Verify the integrity of files using a hash list.', category: 'system-file-management' },
  { name: 'Duplicate File Finder', slug: 'duplicate-file-finder', description: 'Find duplicate files by comparing hashes.', category: 'system-file-management' },
  { name: 'Large File Compressor', slug: 'large-file-compressor', description: 'Compress large files using WebAssembly.', category: 'system-file-management' },
  { name: 'Rename Files in Bulk', slug: 'rename-files-in-bulk', description: 'Rename files in bulk using patterns.', category: 'system-file-management' },
  { name: 'Change File Timestamps', slug: 'change-file-timestamps', description: 'Change the timestamps of files.', category: 'system-file-management' },
  { name: 'File Type Detector', slug: 'file-type-detector', description: 'Detect the MIME type of files.', category: 'system-file-management' },
  { name: 'EXIF Viewer', slug: 'exif-viewer', description: 'View EXIF data from images.', category: 'system-file-management' },
  { name: 'EXIF Remover', slug: 'exif-remover', description: 'Remove EXIF data from images.', category: 'system-file-management' },
  { name: 'PDF/XLSX/DOCX Metadata Scrubber', slug: 'metadata-scrubber', description: 'Scrub metadata from PDF, XLSX, and DOCX files.', category: 'system-file-management' },
  { name: 'Folder Tree Visualizer', slug: 'folder-tree-visualizer', description: 'Visualize a folder tree.', category: 'system-file-management' },
  { name: 'Disk Space Estimator', slug: 'disk-space-estimator', description: 'Estimate disk space for zipped files.', category: 'system-file-management' },
  { name: 'File Icon Previewer', slug: 'file-icon-previewer', description: 'Preview file icons.', category: 'system-file-management' },
  { name: 'Safe File Share Link', slug: 'safe-file-share-link', description: 'Create time-bound safe file share links.', category: 'system-file-management' },
  { name: 'Clipboard Manager', slug: 'clipboard-manager', description: 'A local clipboard manager.', category: 'system-file-management' },
  { name: 'Drag-Drop Converter', slug: 'drag-drop-converter', description: 'A multi-format drag-and-drop converter.', category: 'system-file-management' },
  { name: 'Temporary Files Cleaner', slug: 'temporary-files-cleaner', description: 'A local temporary files cleaner.', category: 'system-file-management' },
  { name: 'Deduplicate CSV Rows by Key', slug: 'deduplicate-csv-rows-by-key', description: 'Deduplicate CSV rows by a key.', category: 'system-file-management' },
  { name: 'JSON Schema Validator', slug: 'json-schema-validator', description: 'Validate JSON against a schema.', category: 'system-file-management' },
  { name: 'Batch Replace in Files', slug: 'batch-replace-in-files', description: 'Perform batch replace operations in files.', category: 'system-file-management' },
  { name: 'Text Encoding Converter', slug: 'text-encoding-converter', description: 'Convert text encoding (UTF-8, UTF-16, etc.).', category: 'system-file-management' },
  { name: 'Checksum List Generator', slug: 'checksum-list-generator', description: 'Generate a list of checksums for files.', category: 'system-file-management' },
  { name: 'File Size Reducer', slug: 'file-size-reducer', description: 'Reduce the size of various file types.', category: 'system-file-management' },
];

const categories: Omit<Category, 'tools'>[] = [
    { name: 'PDF Tools', slug: 'pdf-tools', icon: FileText, color: '346' }, // Red
    { name: 'Image Tools', slug: 'image-tools', icon: Image, color: '206' }, // Sky Blue
    { name: 'Document & File Converters', slug: 'document-file-converters', icon: ArrowRightLeft, color: '122' }, // Light Green
    { name: 'Text & Writing Tools', slug: 'text-writing-tools', icon: PenLine, color: '260' }, // Purple
    { name: 'SEO & Website Tools', slug: 'seo-website-tools', icon: Globe, color: '175' }, // Teal
    { name: 'Finance & Business Calculators', slug: 'finance-business-calculators', icon: Calculator, color: '30' }, // Orange
    { name: 'Math, Science & Academic', slug: 'math-science-academic', icon: FlaskConical, color: '231' }, // Indigo
    { name: 'Data & Developer Utilities', slug: 'data-developer-utilities', icon: Code, color: '280' }, // Violet
    { name: 'Web & URL Utilities', slug: 'web-url-utilities', icon: LinkIcon, color: '220' }, // Dark Blue
    { name: 'Security, Privacy & Hashing', slug: 'security-privacy-hashing', icon: Lock, color: '0' }, // Maroon/Burgundy
    { name: 'Productivity & Planning', slug: 'productivity-planning', icon: CheckSquare, color: '330' }, // Pink
    { name: 'Networking & Diagnostics', slug: 'networking-diagnostics', icon: Network, color: '215' }, // Navy Blue
    { name: 'Color, Design & Branding', slug: 'color-design-branding', icon: Palette, color: '300' }, // Magenta/Fuchsia
    { name: 'OCR, Language & Localization', slug: 'ocr-language-localization', icon: ScanText, color: '50' }, // Yellow
    { name: 'System & File Management', slug: 'system-file-management', icon: Folder, color: '80' }, // Olive Green
];


export const getTools = (): Tool[] => tools;

export const getToolBySlug = (slug: string): Tool | undefined => {
  return tools.find(tool => tool.slug === slug);
};

export const getCategories = (): (Omit<Category, 'tools' | 'color'> & { icon: LucideIcon; color: string; })[] => {
    return categories.map(cat => ({
        ...cat,
        icon: cat.icon as LucideIcon 
    }));
};

export const getCategoryBySlug = (slug: string): (Omit<Category, 'tools' | 'color'> & { icon: LucideIcon, color:string }) | undefined => {
  const cats = getCategories();
  return cats.find(cat => cat.slug === slug);
};

export const getToolsByCategory = (categorySlug: string): Tool[] => {
  return tools.filter(tool => tool.category === categorySlug);
};

export const getToolsByOtherCategories = (categorySlug: string): Tool[] => {
    return tools.filter(tool => tool.category !== categorySlug);
}

export const getAllToolsByCategories = (): Category[] => {
  const allCategories = categories.map(category => ({
    ...category,
    tools: getToolsByCategory(category.slug),
  }));
  return allCategories.filter(category => category.tools.length > 0);
};

export const getTop50Tools = (): Tool[] => {
    const popularToolSlugs = [
      'pdf-to-word', 'image-compressor', 'background-remover', 'image-resizer', 
      'merge-pdf', 'split-pdf', 'word-to-pdf', 'image-to-pdf', 'unlock-pdf',
      'password-generator', 'qr-code-generator', 'json-formatter', 'image-upscaler-ai',
      'face-retouch-ai', 'generative-fill-ai', 'blog-title-generator', 'summarizer',
      'emi-calculator', 'currency-converter', 'whois-lookup', 'dns-lookup', 'ping-test',
      'image-to-text-ocr', 'language-detector', 'grammar-checker', 'paraphraser',
      'csv-to-json', 'json-to-csv', 'case-converter', 'word-counter', 'domain-availability-checker',
      'unit-converter', 'bmi-calculator', 'hash-generator', 'regex-tester',
      'sitemap-generator', 'color-picker', 'gradient-generator', 'image-cropper',
      'jpg-to-png', 'png-to-jpg', 'pdf-to-jpg', 'compress-pdf', 'add-watermark-to-pdf',
      'url-shortener', 'time-zone-converter', 'invoice-generator', 'meme-generator',
      'base64-encoder-decoder', 'html-to-pdf'
    ];
    
    return popularToolSlugs.map(slug => getToolBySlug(slug)).filter((t): t is Tool => !!t);
};
