import { config } from 'dotenv';
config();

import '@/ai/flows/blog-title-generator.ts';
import '@/ai/flows/meta-description-generator.ts';
import '@/ai/flows/pdf-background-remover-ai.ts';
import '@/ai/flows/suggest-related-tools.ts';
import '@/ai/flows/image-background-remover-ai.ts';
import '@/ai/flows/face-retouch.ts';
import '@/ai/flows/image-upscaler.ts';
import '@/ai/flows/summarizer-tool.ts';
import '@/ai V/flows/generative-fill.ts';
import '@/ai/flows/pdf-to-word.ts';
import '@/ai/flows/word-to-pdf.ts';
import '@/ai/flows/pdf-to-excel.ts';
import '@/ai/flows/excel-to-pdf.ts';
import '@/ai/flows/palette-extractor-from-image.ts';
import '@/ai/flows/image-to-text-flow.ts';
import '@/ai/flows/pdf-to-text-flow.ts';
import '@/ai/flows/business-card-ocr-flow.ts';
import '@/ai/flows/language-detector-flow.ts';
import '@/ai/flows/transliteration-flow.ts';
import '@/ai/flows/number-to-words-flow.ts';
import '@/ai/flows/email-extractor-flow.ts';
import '@/ai/flows/pdf-to-powerpoint.ts';
